services:
  my-app:
    image: my-app:local
    build: ./
    ports:
      - 8080:8080
    depends_on:
      redis-server:
        condition: service_healthy
  redis-server:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 10